#ifndef IMAGE_UTIL
#define IMAGE_UTIL

typedef enum _IMAGE_TYPE{
	IMAGE_TYPE_UNKNOWN = 0,
	IMAGE_TYPE_NOT_EXIST = 1,
	IMAGE_TYPE_JPEG = 2,
	IMAGE_TYPE_NORMAL_PNG = 3,
	IMAGE_TYPE_APNG = 4,
	IMAGE_TYPE_COMPLIED_9PNG = 5,
	IMAGE_TYPE_UNCOMPLIED_9PNG = 6,
	IMAGE_TYPE_GFT = 7
}IMAGE_TYPE;

IMAGE_TYPE ic_get_image_type(const char *filePath);

#endif